### ISSUE TITLE
Registrierung Blacklist

### ISSUE THREAD

**Issue by LegendSkyFall** [LegendSkyFall/vkba#24]
Spieler auf der Blacklist können sich trotzdem registrieren.

**Comment by cripiLP** [comment]
Existiert dieser Bug noch?

**Comment by LegendSkyFall** [comment]
Login und Registrierung verhindern, wenn Spieler auf der Blacklist steht.

**Comment by LegendSkyFall** [comment]
Check für Blacklist sowohl im Login- als auch im Registrierungsprozess implementiert (s. Commit 980fcd98296f8ebace4378e6ff910672e92a7838)
