### ISSUE TITLE
Falscher Kontotyp in Einstellungen angegeben

### ISSUE THREAD

**Issue by JanSeW** [LegendSkyFall/vkba#45]
In den Kontoeinstellungen wird statt `Girokonto` `Händlerkonto` angezeigt.

**Comment by LegendSkyFall** [comment]
Danke für's Melden. Das heißt, du besitzt ein Girokonto und auf der Startseite wird dies auch angezeigt, nur unter Einstellungen nicht?

**Comment by JanSeW** [comment]
Fehler behoben. Thxalot
