### ISSUE TITLE
Fehler im Menü der Headbar sowie im Werbeaddon

### ISSUE THREAD

**Issue by JanSeW** [LegendSkyFall/vkba#78]
Es wird ein fehlerhafter Benutzer angezeigt (inkl. falscher Uhrzeit u.ä.). Ebenso funktioniert der Link zu den Transaktionen nicht.
 _Mimimi für heute: CHECK_

![chrome_2017-04-30_12-43-29](https://cloud.githubusercontent.com/assets/16487822/25563745/d1ed2fbc-2da2-11e7-8409-0c2d20069c66.png)

**Comment by JanSeW** [comment]
Leere Seite nach Bestätigen der neuen Werbung. Ebenso kein Eintrag der Werbung. Abrechnung des Werbeaddons wird nicht in den Transaktionen angezeigt.

**Comment by LegendSkyFall** [comment]
Vielen Dank fürs melden.

Das erste mit den Transaktionen ist tatsächlich ein Feature, welches noch nicht implementiert wurde. Danke, dass Du mich wieder daran erinnert hast. Arbeite sowieso gerade an einem Update, dann implementiere ich das gleich.

Das mit der Werbung hingegen scheint wirklich ein Bug zu sein. Auch diesen werde ich mir anschauen und hoffentlich bald fixen können.

**Comment by LegendSkyFall** [comment]
- [x] Implementieren eines Status für Transaktionen (ungelesen/neu)

- [x] Neue Transaktionen anzeigen lassen

- [x] Alle Transaktionen einsehen -> Transaktionsseite

Werbe-Bug ausgelagert zu #83

**Comment by LegendSkyFall** [comment]
Soeben implementiert worden. Siehe Commit a8818f68c644cb01e8de8bf35f1ffba2d47b92c0
