### ISSUE TITLE
Anzeige 2 Addons, Addons aber 3

### ISSUE THREAD

**Issue by Perflyst** [LegendSkyFall/vkba#81]
![image](https://cloud.githubusercontent.com/assets/26308977/25582912/df457d16-2e8f-11e7-8dd1-16bac77bbb50.png)

![image](https://cloud.githubusercontent.com/assets/26308977/25582922/e8bcb206-2e8f-11e7-8b7e-d6fda655c98a.png)

**Comment by LegendSkyFall** [comment]
Die Anzahl der AddOns, welche man selbst besitzt, wird nun korrekt kalkuliert und angezeigt (s. Commit 45f39dd6fa46c17e797b90ac6fe938832ad405bd)
