### ISSUE TITLE
spelling mistakes

### ISSUE THREAD

**Issue by Perflyst** [LegendSkyFall/vkba#82]
![image](https://cloud.githubusercontent.com/assets/26308977/25583031/5abe718c-2e90-11e7-801c-8cbae9d72cac.png)

![image](https://cloud.githubusercontent.com/assets/26308977/25583089/92866e76-2e90-11e7-8fbb-49e423cdc32b.png)

**Comment by LegendSkyFall** [comment]
Danke für die Aufmerksamkeit. Ist behoben.
