### ISSUE TITLE
Werbung schalten funktioniert nicht

### ISSUE THREAD

**Issue by Perflyst** [LegendSkyFall/vkba#83]
Man fügt eine Werbung hinzu, bestätigt, aber es wird keine Werbung angezeigt und sie wird auch nicht gespeichert.

**Comment by LegendSkyFall** [comment]
> Leere Seite nach Bestätigen der neuen Werbung. Ebenso kein Eintrag der Werbung. Abrechnung des Werbeaddons wird nicht in den Transaktionen angezeigt.

 #78
