### ISSUE TITLE
oldvkba.legendskyfall.de fehlt

### ISSUE THREAD

**Issue by Perflyst** [LegendSkyFall/vkba#85]
https://oldvkba.legendskyfall.de/ ist nicht mehr vorhanden.
Absicht oder Fehler?

**Comment by LegendSkyFall** [comment]
Gewollt.

oldvkba wurde schon vor längerer Zeit vollständig eingestellt, da die Kompatibilität nur anfangs gewährleistet wurde, um seine Accounts rechtzeitig migrieren zu können. Selbstverständlich haben wir durch das Admininterface aber dennoch die Möglichkeit, die Accounts zu migrieren.

**Comment by LegendSkyFall** [comment]
- [x] Linkverweis auf Migrieren entfernen.
- [x] In der GitHub Dokumentation darauf hinweisen, dass Migrieren selbst nicht mehr möglich ist.
