### ISSUE TITLE
Migrations Anweisung noch vorhanden

### ISSUE THREAD

**Issue by Perflyst** [LegendSkyFall/vkba#87]
Der Link geht zwar nicht mehr, die Anweisung ist aber dennoch da.
![vkba](https://cloud.githubusercontent.com/assets/26308977/25771246/4f04e366-324c-11e7-85a0-70e97a5fc33d.png)

**Comment by LegendSkyFall** [comment]
Das wurde im letzten Commit 5f3a2bb60d8e5225f6b95126241891c45269a5eb bereits behoben, das Update wird in Kürze, gemeinsam mit einigen weiteren Änderungen, dann auch für Euch online gestellt.
