### ISSUE TITLE
Link bei Anleitung nach falscher Eingabe nicht mehr vorhanden

### ISSUE THREAD

**Issue by Perflyst** [LegendSkyFall/vkba#88]
Der Link ist nicht mehr vorhanden
![vkba_1](https://cloud.githubusercontent.com/assets/26308977/25771249/6d92085e-324c-11e7-98f8-ff90204fed18.png)

**Comment by LegendSkyFall** [comment]
Danke.

Behoben im Commit 78d964c3bf2916d7800fc4e945e9857964c56f69.
