### ISSUE TITLE
Copyright veraltet nach Login (Startseite und Co.)

### ISSUE THREAD

**Issue by Perflyst** [LegendSkyFall/vkba#93]
![image](https://cloud.githubusercontent.com/assets/26308977/26696272/2387981a-470e-11e7-9588-0f80b1f2c1e7.png)

Sollte eigentlich schon gefixt sein, ist es aber nicht!

**Comment by LegendSkyFall** [comment]
Richtig, das wurde im Commit 5f3a2bb60d8e5225f6b95126241891c45269a5eb bereits behoben. Das Update wird allerdings erst mit weiteren Updates gemeinsam für Euch in den kommenden Tagen online gestellt.
